
const products = [

    {
        "id": 1,
        "image": require("./images/teknoloji/teknoloji_1.jpg"),
        "title": "Mackbook Pro",
        "price": 14000,
        "category": "technology",
        "count": 1,
    },
    {
        "id": 2,
        "image": require("./images/teknoloji/teknoloji_3.jpg"),
        "title": "Huawei Matebook D14",
        "price": 9500,
        "category": "technology",
        "count": 1,
    },
    {
        "id": 3,
        "image": require("./images/teknoloji/teknoloji_9.jpg"),
        "title": "Vestel TV",
        "price": 7200,
        "category": "technology",
        "count": 1,
    },
    {
        "id": 4,
        "image": require("./images/teknoloji/teknoloji_7.jpg"),
        "title": "Regal TV",
        "price": 7600,
        "category": "technology",
        "count": 1,
    },
    {
        "id": 5,
        "image": require("./images/teknoloji/teknoloji_6.jpg"),
        "title": "Redmi Note 10S",
        "price": 4800,
        "category": "technology",
        "count": 1,
    },
    {
        "id": 6,
        "image": require("./images/teknoloji/teknoloji_2.jpg"),
        "title": "Huawei Matebook D15",
        "price": 7500,
        "category": "technology",
        "count": 1,
    },
    {
        "id": 7,
        "image": require("./images/teknoloji/teknoloji_8.jpg"),
        "title": " Vestel TV",
        "price": 14000,
        "category": "technology",
        "count": 1,
    },
    {
        "id": 8,
        "image": require("./images/moda/moda_1.jpg"),
        "title": "Yesil Mont",
        "price": 450,
        "category": "fashion",
        "count": 1,
    },
    {
        "id": 9,
        "image": require("./images/moda/moda_2.jpg"),
        "title": "Jack Jones Sweatshirt",
        "price": 160,
        "category": "fashion",
        "count": 1,
    },
    {
        "id": 10,
        "image": require("./images/moda/moda_6.jpg"),
        "title": "Lacivert T-shirt",
        "price": 75,
        "category": "fashion",
        "count": 1,
    },
    {
        "id": 11,
        "image": require("./images/moda/moda_4.jpg"),
        "title": "Kislik Mont",
        "price": 550,
        "category": "fashion",
        "count": 1,
    },
    {
        "id": 12,
        "image": require("./images/moda/moda_5.jpg"),
        "title": "Deri Ceket",
        "price": 680,
        "category": "fashion",
        "count": 1,
    },
    {
        "id": 13,
        "image": require("./images/aksesuar/aksesuar_1.jpg"),
        "title": "Aqua Saat",
        "price": 110,
        "category": "accessories",
        "count": 1,
    },
    {
        "id": 14,
        "image": require("./images/aksesuar/aksesuar_2.jpg"),
        "title": "Spectrum Saat",
        "price": 98,
        "category": "accessories",
        "count": 1,
    },
    {
        "id": 15,
        "image": require("./images/aksesuar/aksesuar_5.jpg"),
        "title": "Jenny Bileklik",
        "price": 30,
        "category": "accessories",
        "count": 1,
    },
    {
        "id": 16,
        "image": require("./images/aksesuar/aksesuar_3.jpg"),
        "title": "Halka Kupe",
        "price": 25,
        "category": "accessories",
        "count": 1,
    },
    {
        "id": 17,
        "image": require("./images/aksesuar/aksesuar_4.jpg"),
        "title": "Zincir Kolye",
        "price": 30,
        "category": "accessories",
        "count": 1,
    },
    {
        "id": 18,
        "image": require("./images/aksesuar/aksesuar_6.jpg"),
        "title": "Jenny Bileklik",
        "price": 45,
        "category": "accessories",
        "count": 1,
    }
]

export default products;
