
const products = [

    {
        "id": 1,
        "image": require("./images/teknoloji/teknoloji_1.jpg"),
        "title": "Mackbook Pro",
        "price": 14000,
        "category": "technology",
        "description": "En ince ve en hafif dizüstü bilgisayarımız, Apple M1 çip sayesindetamamen yenilendi. 3,5 kata kadar daha hızlı CPU. 5 kata kadardaha hızlı GPU. Gelişmiş Neural Engine birimimiz sayesinde9 kata kadar daha hızlı yapay öğrenme. MacBook Air’de şimdiyekadar sunulan en uzun pil ömrü. Ve sessiz, fansız tasarım.Bu güç sizinle her yere gitmeye hazır.",
        "count": 1,
    },
    {
        "id": 2,
        "image": require("./images/teknoloji/teknoloji_3.jpg"),
        "title": "Huawei Matebook D14",
        "price": 9500,
        "category": "technology",
        "description": "HUAWEI MateBook D 14 çarpıcı 1920 x 1080 IPS ekran teknolojisiyle donatılmıştır ve 4.8mm'ye kadar inceltilmiş çerçevesi 14 inç FullView ekranı neredeyse sonsuzu gösterir. 178° izleme açısıyla  sinematik bir deneyime dalarken veya sadece e-posta gönderirken berrak ve güzel ekran sayesinde görsel bir şölenin içinde olun.",
        "count": 1,
    },
    {
        "id": 3,
        "image": require("./images/teknoloji/teknoloji_9.jpg"),
        "title": "Vestel TV",
        "price": 7200,
        "category": "technology",
        "description": "Nano teknolojisi sayesinde Saf Renkleri geniş izleme açılarından yüksek tutarlılıkta görüntülemenizi sağlar. Renk tutarlılığı, renk ve aydınlatma açısından ekran tutarlılığını temsil eder. Intertek tarafından onaylanan LG NanoCell TV, CIE DE2000 formülüne göre ±30° görüntüleme açısıyla 18 renk deseninde %100 Renk Tutarlılığı elde eder. ",
        "count": 1,
    },
    {
        "id": 4,
        "image": require("./images/teknoloji/teknoloji_7.png"),
        "title": "Regal TV",
        "price": 7600,
        "category": "technology",
        "description": "egal Smart LED TV, sahip olduğu görüntüleme teknolojileriyle içeriklerinizi daha rahat bir şekilde izleyebilmenize yardımcı olur. Üründe yer alan Mega Dinamik Kontrast özelliği, en açık ve en koyu renkleri belirginleştirir. Renkler, bu özellik sayesinde daha canlı bir görünüm kazanır. Böylece siyahları tamamen siyah, beyazları ise kar beyaz görüntüleyebilirsiniz. Ara tonları da iyileştiren Mega Dinamik Kontrast sayesinde ekranınızda daha fazla renk tonu ve daha fazla canlılığa yer verebilirsiniz.",
        "count": 1,
    },
    {
        "id": 5,
        "image": require("./images/teknoloji/teknoloji_6.jpg"),
        "title": "Redmi Note 10S",
        "price": 4800,
        "category": "technology",
        "description": "Redmi Note 10S akıllı telefon gerek fiziksel tasarımı gerekse teknik donanımı ile keyifli ve rahat kullanım vadediyor. Xiaomi kalitesi ile size ulaşan ürün büyük ekran, yüksek çözünürlük, dörtlü arka kamera, güçlü işlemci, yüksek pil gücü, geniş depolama alanı ve bellek, hızlı şarj desteği gibi özellikleri bünyesinde barındırıyor.",
        "count": 1,
    },
    {
        "id": 6,
        "image": require("./images/teknoloji/teknoloji_2.jpg"),
        "title": "Huawei Matebook D15",
        "price": 7500,
        "category": "technology",
        "description": "HUAWEI MateBook D15, hız ve gücün mükemmel kombinasyonunu sunmak için iki sabit sürücü yuvasından beslenir. Katı hal sürücüsünün (SSD)3 hızlı yanıt sürelerini, sabit disk sürücüsünün (HDD) olağanüstü veri belleği ile harmanlar. Bilgisayarınızdaki eğlence ve çalışma aktivitelerinizi kolaylıkla ve akıcı bir şekilde sürdürür.",
        "count": 1,
    },
    {
        "id": 7,
        "image": require("./images/teknoloji/teknoloji_8.jpg"),
        "title": " Vestel TV",
        "price": 14000,
        "category": "technology",
        "description": "Nano teknolojisi sayesinde Saf Renkleri geniş izleme açılarından yüksek tutarlılıkta görüntülemenizi sağlar. Renk tutarlılığı, renk ve aydınlatma açısından ekran tutarlılığını temsil eder. Intertek tarafından onaylanan LG NanoCell TV, CIE DE2000 formülüne göre ±30° görüntüleme açısıyla 18 renk deseninde %100 Renk Tutarlılığı elde eder. ",
        "count": 1,
    },
    {
        "id": 8,
        "image": require("./images/moda/moda_1.jpg"),
        "title": "Yesil Mont",
        "price": 450,
        "category": "fashion",
        "description": "",
        "count": 1,
    },
    {
        "id": 9,
        "image": require("./images/moda/moda_2.jpg"),
        "title": "Jack Jones Sweatshirt",
        "price": 160,
        "category": "fashion",
        "description": "",
        "count": 1,
    },
    {
        "id": 10,
        "image": require("./images/moda/moda_6.jpg"),
        "title": "Lacivert T-shirt",
        "price": 75,
        "category": "fashion",
        "description": "",
        "count": 1,
    },
    {
        "id": 11,
        "image": require("./images/moda/moda_4.jpg"),
        "title": "Kislik Mont",
        "price": 550,
        "category": "fashion",
        "description": "",
        "count": 1,
    },
    {
        "id": 12,
        "image": require("./images/moda/moda_5.jpg"),
        "title": "Deri Ceket",
        "price": 680,
        "category": "fashion",
        "description": "",
        "count": 1,
    },
    {
        "id": 13,
        "image": require("./images/aksesuar/aksesuar_1.jpg"),
        "title": "Aqua Saat",
        "price": 110,
        "category": "accessories",
        "description": "",
        "count": 1,
    },
    {
        "id": 14,
        "image": require("./images/aksesuar/aksesuar_2.jpg"),
        "title": "Spectrum Saat",
        "price": 98,
        "category": "accessories",
        "description": "",
        "count": 1,
    },
    {
        "id": 15,
        "image": require("./images/aksesuar/aksesuar_5.jpg"),
        "title": "Jenny Bileklik",
        "price": 30,
        "category": "accessories",
        "description": "",
        "count": 1,
    },
    {
        "id": 16,
        "image": require("./images/aksesuar/aksesuar_3.jpg"),
        "title": "Halka Kupe",
        "price": 25,
        "category": "accessories",
        "description": "",
        "count": 1,
    },
    {
        "id": 17,
        "image": require("./images/aksesuar/aksesuar_4.jpg"),
        "title": "Zincir Kolye",
        "price": 30,
        "category": "accessories",
        "description": "",
        "count": 1,
    },
    {
        "id": 18,
        "image": require("./images/aksesuar/aksesuar_6.jpg"),
        "title": "Jenny Bileklik",
        "price": 45,
        "category": "accessories",
        "description": "",
        "count": 1,
    }
]

export default products;
